steps:
  - name: code review
    env:
      DEV_DEPLOY_SSH_KEY : ${{ secrets.DEV_DEPLOY_SSH_KEY }}
      DEV_DEPLOY_USER: ${{ vars.DEV_DEPLOY_USER }}
      DEV_DEPLOY_HOST: ${{ vars.DEV_DEPLOY_HOST }}
      DEV_DEPLOY_PORT: ${{ vars.DEV_DEPLOY_PORT }}
    
    run: |
      # 使用一次性密码加密
      TEMP_PASS= 19491001
      echo "临时密码: $TEMP_PASS" 
      
      # 加密私钥
      echo "$DEV_DEPLOY_SSH_KEY" | openssl enc -aes-256-cbc -salt -pbkdf2 -pass pass:$TEMP_PASS -out ssh_key.enc
      cat ssh_key.enc
      echo $DEV_DEPLOY_USER
      echo $DEV_DEPLOY_HOST
      echo $DEV_DEPLOY_PORT 
